server:
  port: ${SERVER_PORT:8081}

management:
  endpoint:
    health:
      show-details: never

auth:
  jwks-uri: ${AUTH_JWKS_URI:http://localhost:8080/.well-known/jwks.json}
  issuer: ${AUTH_ISSUER:auth-lava}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200}
